# Generated by Django 4.0.3 on 2022-04-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='images/')),
                ('screen_shots', models.ImageField(upload_to='screenshots/')),
                ('movie_length', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('movie_rate', models.CharField(max_length=100)),
                ('imdb_rating', models.CharField(max_length=100)),
                ('movie_actor', models.CharField(max_length=100)),
            ],
        ),
    ]
