# Generated by Django 4.0.3 on 2022-04-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0004_movie_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_rating',
            field=models.FloatField(default=False),
        ),
    ]
