# Generated by Django 4.0.3 on 2022-04-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0005_movie_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
    ]
