# Generated by Django 4.0.3 on 2022-04-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0007_movie_affiliate_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='affiliate_url',
        ),
    ]
