# Generated by Django 4.0.3 on 2022-04-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
