# Generated by Django 4.0.3 on 2022-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0010_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
