# Generated by Django 4.0.3 on 2022-04-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0011_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='movie_desc',
        ),
    ]
