# Generated by Django 4.0.3 on 2022-04-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0012_rename_description_movie_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_page',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
