# Generated by Django 4.0.3 on 2022-04-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0013_movie_movie_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_page',
            new_name='movie_slug',
        ),
    ]
