# Generated by Django 4.0.3 on 2022-04-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0014_rename_movie_page_movie_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_bg',
            field=models.ImageField(blank=True, default='../static/default_avatar.png', upload_to='background'),
        ),
    ]
