# Generated by Django 4.0.3 on 2022-04-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenTicket', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='affiliate_url',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
